In [2]:
import pandas as pd


station_data = pd.read_csv('/Users/danielpatel2000/Desktop/USF/Module 1/692 - Data Aquisition/Project/Example Data/station_data_file.csv')
# (ignore) underground_levels_data = pd.read_csv('/Users/danielpatel2000/Desktop/USF/Module 1/692 - Data Aquisition/Project/Example Data/underground_levels_data_file.csv')
weather_hourly = pd.read_parquet('/Users/danielpatel2000/Desktop/USF/Module 1/692 - Data Aquisition/Project/Example Data/weather-processed-weather_hourly.parquet')
delays = pd.read_csv('/Users/danielpatel2000/Desktop/USF/Module 1/692 - Data Aquisition/Project/Example Data/mbta_station_hour_panel_2025-03-01_to_2025-06-07.csv')
ridership = pd.read_csv('/Users/danielpatel2000/Desktop/USF/Module 1/692 - Data Aquisition/Project/Example Data/GSE_hourly_all.csv')

In [7]:
dt = pd.to_datetime(ridership["datetime"])
print("ridership range:", dt.min(), "->", dt.max())
print("delays range:   ", delays["hour_utc"].min(), "->", delays["hour_utc"].max())

# Average entries by hour of day: the low point shows which clock it's on
print(ridership.groupby(dt.dt.hour)["hourly_entries"].mean().round(0))

ridership range: 2025-08-01 00:00:00 -> 2026-07-31 23:00:00
delays range:    2025-03-01 06:00:00+00:00 -> 2025-06-08 06:00:00+00:00
datetime
0      28.0
1       8.0
2       3.0
3       3.0
4       6.0
5      75.0
6     155.0
7     260.0
8     310.0
9     206.0
10    169.0
11    174.0
12    197.0
13    216.0
14    264.0
15    319.0
16    373.0
17    395.0
18    270.0
19    193.0
20    145.0
21    142.0
22    121.0
23     79.0
Name: hourly_entries, dtype: float64

In [2]:
station_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10298 entries, 0 to 10297
Data columns (total 19 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   stop_id              10298 non-null  object
 1   stop_code            7037 non-null   float64
 2   stop_name            10298 non-null  object
 3   stop_desc            3390 non-null   object
 4   platform_code        376 non-null    object
 5   platform_name        1128 non-null   object
 6   stop_lat             9693 non-null   float64
 7   stop_lon             9693 non-null   float64
 8   zone_id              7617 non-null   object
 9   stop_address         315 non-null    object
 10  stop_url             7740 non-null   object
 11  level_id             2737 non-null   object
 12  location_type        10298 non-null  int64
 13  parent_station       3192 non-null   object
 14  wheelchair_boarding  10298 non-null  int64
 15  municipality         10298 non-null  object
 16  on_street            6873 non-null   object
 17  at_street            6035 non-null   object
 18  vehicle_type         7765 non-null   float64
dtypes: float64(4), int64(2), object(13)
memory usage: 1.5+ MB

In [3]:
station_data.head()

,stop_id,stop_code,stop_name,stop_desc,platform_code,platform_name,stop_lat,stop_lon,zone_id,stop_address,stop_url,level_id,location_type,parent_station,wheelchair_boarding,municipality,on_street,at_street,vehicle_type
0,1,1.0,Washington St opp Ruggles St,NaN,NaN,NaN,42.330957,-71.082754,ExpressBus-Downtown,NaN,https://www.mbta.com/stops/1,NaN,0,NaN,1,Boston,Washington Street,Ruggles Street,3.0
1,10,10.0,Theo Glynn Way @ Newmarket Sq,NaN,NaN,NaN,42.330555,-71.068787,LocalBus,NaN,https://www.mbta.com/stops/10,NaN,0,NaN,1,Boston,Theodore Glynn Way,Newmarket Square,3.0
2,10000,10000.0,Tremont St opp Temple Pl,NaN,NaN,NaN,42.355692,-71.062911,LocalBus,NaN,https://www.mbta.com/stops/10000,NaN,0,NaN,1,Boston,Tremont Street,Temple Place,3.0
3,10003,10003.0,Albany St opp Randall St,NaN,NaN,NaN,42.331591,-71.076237,LocalBus,NaN,https://www.mbta.com/stops/10003,NaN,0,NaN,1,Boston,Albany Street,Randall Street,3.0
4,10005,10005.0,Albany St opp E Concord St,NaN,NaN,NaN,42.335017,-71.071280,LocalBus,NaN,https://www.mbta.com/stops/10005,NaN,0,NaN,1,Boston,Albany Street,NaN,3.0

In [4]:
station_data.describe()

,stop_code,stop_lat,stop_lon,location_type,wheelchair_boarding,vehicle_type
count,7037.000000,9693.000000,9693.000000,10298.000000,10298.000000,7765.000000
mean,16106.983231,42.352499,-71.079843,0.651971,0.986696,2.863490
std,30323.915062,0.103157,0.101169,1.188574,0.283086,0.527124
min,1.000000,41.581095,-71.848488,0.000000,0.000000,0.000000
25%,2884.000000,42.293060,-71.131791,0.000000,1.000000,3.000000
50%,5765.000000,42.356247,-71.073983,0.000000,1.000000,3.000000
75%,10582.000000,42.412626,-71.027677,0.000000,1.000000,3.000000
max,883321.000000,42.797837,-70.276583,3.000000,2.000000,4.000000

In [5]:
weather_hourly.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1461000 entries, 0 to 1460999
Data columns (total 15 columns):
 #   Column              Non-Null Count    Dtype
---  ------              --------------    -----
 0   location            1461000 non-null  object
 1   observed_at_utc     1461000 non-null  object
 2   observed_at_local   1461000 non-null  object
 3   latitude            1461000 non-null  float64
 4   longitude           1461000 non-null  float64
 5   temperature_2m      1461000 non-null  float64
 6   rain                1461000 non-null  float64
 7   snowfall            1461000 non-null  float64
 8   wind_gusts_10m      1461000 non-null  float64
 9   visibility          1461000 non-null  float64
 10  is_precipitating    1461000 non-null  int64
 11  is_raining          1461000 non-null  int64
 12  is_snowing          1461000 non-null  int64
 13  is_freezing_precip  1461000 non-null  int64
 14  ingested_at_utc     1461000 non-null  object
dtypes: float64(7), int64(4), object(4)
memory usage: 167.2+ MB

In [5]:
ridership['stop_id'].head(15)

0     place-alfcl
1     place-andrw
2     place-aport
3     place-aqucl
4     place-armnl
5     place-asmnl
6     place-astao
7     place-bbsta
8     place-bmmnl
9     place-bomnl
10    place-boyls
11    place-brdwy
12    place-brntn
13    place-ccmnl
14    place-chmnl
Name: stop_id, dtype: object

In [ ]:
ridership.stop_id uses the same IDs as delays.parent_station

In [6]:
weather_hourly.head()

,location,observed_at_utc,observed_at_local,latitude,longitude,temperature_2m,rain,snowfall,wind_gusts_10m,visibility,is_precipitating,is_raining,is_snowing,is_freezing_precip,ingested_at_utc
0,Airport,2025-06-01T00:00:00+00:00,2025-05-31T20:00:00-04:00,42.38335,-71.016525,14.6,0.0,0.0,57.6,22600.0,0,0,0,0,2026-10-02T01:21:05.292016+00:00
1,Airport,2025-06-01T01:00:00+00:00,2025-05-31T21:00:00-04:00,42.38335,-71.016525,13.3,0.0,0.0,50.4,21900.0,0,0,0,0,2026-10-02T01:21:05.292016+00:00
2,Airport,2025-06-01T02:00:00+00:00,2025-05-31T22:00:00-04:00,42.38335,-71.016525,12.1,0.0,0.0,51.8,18900.0,0,0,0,0,2026-10-02T01:21:05.292016+00:00
3,Airport,2025-06-01T03:00:00+00:00,2025-05-31T23:00:00-04:00,42.38335,-71.016525,11.1,0.0,0.0,51.1,12100.0,0,0,0,0,2026-10-02T01:21:05.292016+00:00
4,Airport,2025-06-01T04:00:00+00:00,2025-06-01T00:00:00-04:00,42.38335,-71.016525,10.8,0.0,0.0,47.9,15400.0,0,0,0,0,2026-10-02T01:21:05.292016+00:00

In [7]:
weather_hourly.describe()

,latitude,longitude,temperature_2m,rain,snowfall,wind_gusts_10m,visibility,is_precipitating,is_raining,is_snowing,is_freezing_precip
count,1.461000e+06,1.461000e+06,1.461000e+06,1.461000e+06,1.461000e+06,1.461000e+06,1.461000e+06,1.461000e+06,1.461000e+06,1.461000e+06,1.461000e+06
mean,4.234305e+01,-7.109736e+01,1.332639e+01,7.956660e-02,6.222861e-03,2.455935e+01,2.798538e+04,4.691102e-02,3.757837e-02,1.314579e-02,9.180014e-03
std,3.862391e-02,4.962749e-02,1.100080e+01,9.301971e-01,7.509677e-02,1.366093e+01,1.481157e+04,2.114484e-01,1.901743e-01,1.138990e-01,9.537163e-02
min,4.221319e+01,-7.125709e+01,-2.060000e+01,0.000000e+00,0.000000e+00,4.000000e-01,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
25%,4.232875e+01,-7.112138e+01,4.900000e+00,0.000000e+00,0.000000e+00,1.480000e+01,1.660000e+04,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
50%,4.234697e+01,-7.110704e+01,1.510000e+01,0.000000e+00,0.000000e+00,2.160000e+01,2.530000e+04,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
75%,4.236517e+01,-7.106180e+01,2.170000e+01,0.000000e+00,0.000000e+00,3.200000e+01,3.790000e+04,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
max,4.242441e+01,-7.099839e+01,4.000000e+01,6.520000e+01,3.150000e+00,1.156000e+02,9.000000e+04,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00

In [8]:
delays.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 245974 entries, 0 to 245973
Data columns (total 11 columns):
 #   Column                     Non-Null Count   Dtype
---  ------                     --------------   -----
 0   parent_station             245974 non-null  object
 1   hour_local                 245974 non-null  object
 2   hour_utc                   245974 non-null  object
 3   n_arrivals                 245974 non-null  int64
 4   n_travel_obs               245974 non-null  int64
 5   excess_travel_min_median   244483 non-null  float64
 6   excess_travel_min_mean     244483 non-null  float64
 7   excess_travel_min_p90      244483 non-null  float64
 8   excess_travel_min_sum      244483 non-null  float64
 9   n_headway_obs              245974 non-null  int64
 10  excess_headway_min_median  238649 non-null  float64
dtypes: float64(5), int64(3), object(3)
memory usage: 20.6+ MB

In [16]:
delays.tail()

,parent_station,hour_local,hour_utc,n_arrivals,n_travel_obs,excess_travel_min_median,excess_travel_min_mean,excess_travel_min_p90,excess_travel_min_sum,n_headway_obs,excess_headway_min_median
245969,place-wrnst,2025-06-07 21:00:00-04:00,2025-06-08 01:00:00+00:00,10,10,-1.050000,-1.120000,-0.628333,-11.200000,10,4.350000
245970,place-wrnst,2025-06-07 22:00:00-04:00,2025-06-08 02:00:00+00:00,8,8,-1.041667,-1.108333,-0.528333,-8.866667,8,5.166667
245971,place-wrnst,2025-06-07 23:00:00-04:00,2025-06-08 03:00:00+00:00,12,12,-0.666667,-0.829167,-0.555000,-9.950000,12,2.908333
245972,place-wrnst,2025-06-08 00:00:00-04:00,2025-06-08 04:00:00+00:00,8,8,-0.591667,-0.581250,-0.486667,-4.650000,8,4.683333
245973,place-wrnst,2025-06-08 01:00:00-04:00,2025-06-08 05:00:00+00:00,1,1,-0.683333,-0.683333,-0.683333,-0.683333,1,7.516667

In [10]:
delays.describe()

,n_arrivals,n_travel_obs,excess_travel_min_median,excess_travel_min_mean,excess_travel_min_p90,excess_travel_min_sum,n_headway_obs,excess_headway_min_median
count,245974.000000,245974.000000,244483.000000,244483.000000,244483.000000,244483.000000,245974.000000,238649.000000
mean,16.690776,15.313988,-0.710844,-0.656468,-0.133783,-11.059311,14.597917,0.449526
std,15.726199,10.947788,0.841384,0.874237,1.374721,11.648713,9.950230,2.849684
min,1.000000,0.000000,-4.716667,-4.666667,-4.583333,-97.616667,0.000000,-24.283333
25%,11.000000,10.000000,-1.083333,-1.020833,-0.635000,-15.583333,9.000000,-0.500000
50%,14.000000,13.000000,-0.733333,-0.729630,-0.346667,-9.250000,13.000000,0.025000
75%,18.000000,17.000000,-0.458333,-0.427778,0.098333,-4.150000,17.000000,0.741667
max,1229.000000,93.000000,57.050000,57.050000,58.815000,316.983333,87.000000,59.633333

In [11]:
ridership.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 518807 entries, 0 to 518806
Data columns (total 7 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   datetime        518807 non-null  object
 1   day_type        518807 non-null  object
 2   event_day       518807 non-null  bool
 3   stop_id         518807 non-null  object
 4   station_name    518807 non-null  object
 5   lines           518807 non-null  object
 6   hourly_entries  518807 non-null  float64
dtypes: bool(1), float64(1), object(5)
memory usage: 24.2+ MB

In [12]:
ridership.describe()

       hourly_entries
count   518807.000000
mean       190.254793
std        257.432896
min          0.000000
25%         25.000000
50%        109.000000
75%        250.000000
max       4091.000000

In [6]:
ridership.head()

,datetime,day_type,event_day,stop_id,station_name,lines,hourly_entries
0,2025-08-01 00:00:00,weekday,False,place-alfcl,Alewife,Red Line,7.0
1,2025-08-01 00:00:00,weekday,False,place-andrw,Andrew,Red Line,8.0
2,2025-08-01 00:00:00,weekday,False,place-aport,Airport,Blue Line,57.0
3,2025-08-01 00:00:00,weekday,False,place-aqucl,Aquarium,Blue Line,58.0
4,2025-08-01 00:00:00,weekday,False,place-armnl,Arlington,Green Line,22.0